# User profile information
[profile]
name = "First Last"
avatar = "/images/"
description = "Something"
tagline = "Something"

# Theme configuration
[theme]
useBackgroundImage = false
backgroundImage = "/backgrounds/"
backgroundOverlayOpacity = 0.2
backgroundBlur = 0.5

# Social links - each link has a title, url, and icon
[[links]]
title = "Homepage"
url = "https://ychwang.io"
icon = "House"

[[links]]
title = "GitHub"
url = "https://github.com/"
icon = "Github"

[[links]]
title = "LinkedIn"
url = "https://linkedin.com/in/"
icon = "Linkedin"

[[links]]
title = "Contact Me"
url = "mailto:"
icon = "Mail"
